---@meta
-- This file is auto-generated by the engine. Do not edit.

---@class Controllable

---@class TerrainMap
---@field size number
---@field height number
---@field resolution number
---@field map Texture

---@class DirectionalLight
---@field from_position Vec3
---@field color Vec3

---@class Camera
---@field position Vec3
---@field rotation Rotor3
---@field fov_rads number
---@field near number
---@field far number
---@field pitch number
---@field yaw number
---@field aspect_ratio number

---@class PointLight
---@field color Vec3
---@field brightness number
---@field linear number
---@field quadratic number

---@class Time
---@field delta_time number

---@class AmbientLight
---@field color Vec3
---@field intensity number

---@class Transform
---@field position Vec3
---@field rotation Rotor3
---@field scale Vec3

---@class Animation

---@class Animated
---@field time number
---@field animations Animation[]
---@field current_playing Animation?
---@field skeleton Skeleton

---@class Material
---@field albedo Texture

---@class Skeleton

---@class Skybox
---@field material Material

---@class Mesh
---@field animated boolean

---@class Texture

---@class Rotor3
---@field pitch number
---@field yaw number
---@field roll number

---@class Vec3
---@field x number
---@field y number
---@field z number

---@class Collider
---@field type string
---@field data Aabb | Obb

---@class Obb
---@field center_offset Vec3
---@field half_extents Vec3

---@class Aabb
---@field min Vec3
---@field max Vec3

---@class RigidBody
---@field velocity Vec3

---@class Slider
---@field label string
---@field value number
---@field min number
---@field max number

---@class UIStuff
---@field sliders Slider[]

