---@meta
-- This file is auto-generated by the engine. Do not edit.

---@class Obb
---@field center_offset Vec3
---@field half_extents Vec3

---@class Aabb
---@field min Vec3
---@field max Vec3

---@class RigidBody
---@field velocity Vec3

---@class BlendTo
---@field delay number
---@field target Animation

---@class Blend
---@field blend_progress number
---@field delay number
---@field next_mode PlaybackMode

---@class Then
---@field next_mode PlaybackMode

---@class Texture

---@class Skybox
---@field material Material

---@class Animated
---@field skeleton Skeleton
---@field mode PlaybackMode
---@field speed number
---@field blend_duration number
---@field time number
---@field stop_blend_progress number
---@field available_animations Animation[]

---@class Mesh
---@field animated boolean

---@class Animation

---@class Material
---@field albedo Texture
---@field alpha_clip number?

---@class Skeleton

---@class TerrainMap
---@field size number
---@field height number
---@field resolution number
---@field map Texture

---@class Controllable
---@field speed number
---@field sprint_speed number

---@class Vec3
---@field x number
---@field y number
---@field z number

---@class Rotor3
---@field pitch number
---@field yaw number
---@field roll number

---@class EntityName
---@field name string

---@class Time
---@field delta_time number

---@class PointLight
---@field color Vec3
---@field brightness number
---@field linear number
---@field quadratic number

---@class Transform
---@field position Vec3
---@field rotation Rotor3
---@field scale Vec3

---@class Camera
---@field position Vec3
---@field rotation Rotor3
---@field fov_rads number
---@field near number
---@field far number
---@field pitch number
---@field yaw number
---@field aspect_ratio number

---@class AmbientLight
---@field color Vec3
---@field intensity number

---@class DirectionalLight
---@field from_position Vec3
---@field color Vec3

---@class UISchema
---@field windows WindowSchema[]

---@class WindowSchema
---@field name string
---@field fields LayoutItem[]

---@class CameraOffset
---@field offset Vec3

---@class UIStuff
---@field widgets table<string, Widget>
---@field schema UISchema
---@field show_settings boolean

---@class TextInput
---@field value string
---@field label string?

---@class NumberInput
---@field value number
---@field min number
---@field max number
---@field label string?

---@class Button
---@field clicked boolean
---@field label string?

---@class Label
---@field text string

---@class Row
---@field items LayoutItem[]

---@class Slider
---@field value number
---@field min number
---@field max number
---@field label string?

---@class Collumn
---@field items LayoutItem[]

---@class Config
---@field gravity_strength number

---@class Collider_Aabb
---@field type "Aabb"
---@field data Aabb

---@class Collider_Obb
---@field type "Obb"
---@field data Obb

---@alias Collider Collider_Aabb | Collider_Obb

---@class PlaybackMode_Loop
---@field type "Loop"
---@field data Animation

---@class PlaybackMode_Once
---@field type "Once"
---@field data Animation

---@class PlaybackMode_Clamp
---@field type "Clamp"
---@field data Animation

---@class PlaybackMode_Then
---@field type "Then"
---@field data Animation, Then

---@class PlaybackMode_Blend
---@field type "Blend"
---@field data Animation, Blend

---@class PlaybackMode_Stopped
---@field type "Stopped"

---@alias PlaybackMode PlaybackMode_Loop | PlaybackMode_Once | PlaybackMode_Clamp | PlaybackMode_Then | PlaybackMode_Blend | PlaybackMode_Stopped

---@class LayoutItem_Field
---@field type "Field"
---@field data string

---@class LayoutItem_Row
---@field type "Row"
---@field data Row

---@class LayoutItem_Column
---@field type "Column"
---@field data Collumn

---@alias LayoutItem LayoutItem_Field | LayoutItem_Row | LayoutItem_Column

---@class Widget_Slider
---@field type "Slider"
---@field data Slider

---@class Widget_Button
---@field type "Button"
---@field data Button

---@class Widget_Label
---@field type "Label"
---@field data Label

---@class Widget_TextInput
---@field type "TextInput"
---@field data TextInput

---@class Widget_NumberInput
---@field type "NumberInput"
---@field data NumberInput

---@class Widget_Separator
---@field type "Separator"

---@alias Widget Widget_Slider | Widget_Button | Widget_Label | Widget_TextInput | Widget_NumberInput | Widget_Separator

