use std::{any::TypeId, collections::HashMap, sync::Arc};

use proc_macros::LuaVal;
use ultraviolet::{self as uv};

use crate::{
    core::Engine,
    ecs::{DynamicComponent, EntityId, QueryInfo, World},
};

pub struct LuaVM {
    lua: mlua::Lua,
    path: String,
    type_registry: Arc<TypeRegistry>,
    last_modified: std::time::SystemTime,
}
pub fn write_lua_docs(path: &str) {
    let mut output = String::new();

    output.push_str("---@meta\n");
    output.push_str("-- This file is auto-generated by the engine. Do not edit.\n\n");

    for reg in inventory::iter::<LuaTypeDoc>() {
        output.push_str(&format!("---@class {}\n", reg.name));

        for (field_name, field_type) in reg.fields {
            let lua_type = match *field_type {
                "f32" | "f64" | "i32" | "i64" | "u32" | "u64" | "isize" | "usize" => "number",
                "String" => "string",
                "bool" => "boolean",
                other => other,
            };
            output.push_str(&format!("---@field {} {}\n", field_name, lua_type));
        }

        output.push('\n');
    }

    std::fs::write(path, output).expect("failed to write lua docs");
}

impl LuaVM {
    pub fn new(path: &str) -> LuaVM {
        write_lua_docs("data/scripts/typedef.lua");
        let lua = mlua::Lua::new();
        let src = std::fs::read_to_string(path).unwrap();
        let err = lua.load(src).exec();
        err.print_on_error();
        dbg!(&path);
        Self {
            lua: lua,
            path: path.to_string(),
            type_registry: Arc::new(TypeRegistry::new()),
            last_modified: std::time::SystemTime::now(),
        }
    }

    pub fn run_script(
        &mut self,
        world: &mut World,
        engine: &mut Engine,
        entry_point: &str,
    ) -> Result<(), mlua::Error> {
        self.maybe_reload()?;
        let function: mlua::Function = self.lua.globals().get(entry_point)?;
        // make the lua user data
        let lua_world_ud = self.lua.create_userdata(LuaWorld {
            world: world as *mut World,
            query_active: false,
            type_registry: self.type_registry.clone(),
        })?;
        let lua_engine_ud = self.lua.create_userdata(LuaEngine {
            engine: engine as *mut Engine,
        })?;
        function.call::<()>((lua_world_ud, lua_engine_ud))?;
        Ok(())
    }

    pub fn maybe_reload(&mut self) -> Result<(), mlua::Error> {
        let modified = std::fs::metadata(&self.path)?.modified()?;
        if modified > self.last_modified {
            let src = std::fs::read_to_string(&self.path)?;
            self.lua.load(src).exec()?;
            self.last_modified = modified;
        }

        Ok(())
    }
}

pub struct LuaWorld {
    pub world: *mut World,
    pub type_registry: Arc<TypeRegistry>,
    query_active: bool,
}
pub struct LuaEngine {
    engine: *mut Engine,
}

pub trait LuaSeralize
where
    Self: Sized,
{
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self>;
    fn to_lua(&mut self, lua: &mlua::Lua) -> mlua::Result<mlua::Value>;
}

type LuaFromPtrFn = fn(*mut u8, &mlua::Lua) -> mlua::Result<mlua::Value>;
type DynComponentFromLuaFn = fn(&mlua::Value) -> mlua::Result<Box<dyn DynamicComponent>>;
type DefualtConstructFn = fn() -> Box<dyn DynamicComponent>;
// i should make a trait to handle the conversions to and from lua, to allow for implimenting it on
//:stuff like Vec<T> where T: LuaConvert or something, but thats for later
// because the dynamicboundary is on the registry, but it doesnt need to recurse downward
pub struct TypeRegistration {
    pub name: &'static str,
    pub typeid: TypeId,
    pub lua_from_ptr: LuaFromPtrFn,
    // readback without type information is only ever used to add components to the world
    pub dyn_from_lua: DynComponentFromLuaFn,
    pub default_construct: Option<DefualtConstructFn>,
}

pub struct TypeRegistry {
    pub registrations: HashMap<String, &'static TypeRegistration>,
}
pub struct LuaTypeDoc {
    pub name: &'static str,
    pub fields: &'static [(&'static str, &'static str)],
}
inventory::collect!(TypeRegistration);
inventory::collect!(LuaTypeDoc);

impl TypeRegistry {
    fn new() -> Self {
        let mut registrations = HashMap::new();
        for item in inventory::iter::<TypeRegistration>() {
            registrations.insert(item.name.to_string(), item);
        }
        TypeRegistry { registrations }
    }
}

impl mlua::UserData for EntityId {}
impl mlua::UserData for LuaWorld {
    fn add_fields<F: mlua::UserDataFields<Self>>(_fields: &mut F) {}

    fn add_methods<M: mlua::UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method(
            "spawn",
            |lua: &mlua::Lua, world: &Self, ()| -> mlua::Result<mlua::AnyUserData> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = ecs_world.spawn();
                lua.create_userdata(entity)
            },
        );
        methods.add_method(
            "get_resource",
            |lua, world, name: String| -> mlua::Result<mlua::Value> {
                let ecs_world = unsafe { &mut *world.world };
                let reg = world.type_registry.registrations.get(&name).ok_or(
                    mlua::Error::RuntimeError(format!("not registered: {}", name)),
                )?;
                let ptr = ecs_world.get_mut_resource_dyn(&reg.typeid).ok_or(
                    mlua::Error::RuntimeError(format!("resource not found: {}", name)),
                )?;
                let raw_ptr = ptr.as_mut() as *mut dyn std::any::Any as *mut u8;
                (reg.lua_from_ptr)(raw_ptr, lua)
            },
        );
        methods.add_method(
            "query",
            |lua: &mlua::Lua, world: &Self, query: mlua::Table| -> mlua::Result<mlua::Value> {
                let ecs_world = unsafe { &mut *world.world };

                let mut req_typeids = Vec::new();
                let req_names: Vec<String> = query
                    .get::<mlua::Table>("req")
                    .unwrap_or(lua.create_table()?)
                    .sequence_values::<String>()
                    .collect::<mlua::Result<_>>()?;
                for name in &req_names {
                    let reg = world.type_registry.registrations.get(name).ok_or(
                        mlua::Error::RuntimeError(format!("type not registered: {}", name)),
                    )?;
                    req_typeids.push(reg.typeid);
                }

                let mut opt_typeids = Vec::new();
                let opt_names: Vec<String> = query
                    .get::<mlua::Table>("opt")
                    .unwrap_or(lua.create_table()?)
                    .sequence_values::<String>()
                    .collect::<mlua::Result<_>>()?;
                for name in &opt_names {
                    let reg = world.type_registry.registrations.get(name).ok_or(
                        mlua::Error::RuntimeError(format!("type not registered: {}", name)),
                    )?;
                    opt_typeids.push(reg.typeid);
                }

                let mut not_typeids = Vec::new();
                let not_names: Vec<String> = query
                    .get::<mlua::Table>("not")
                    .unwrap_or(lua.create_table()?)
                    .sequence_values::<String>()
                    .collect::<mlua::Result<_>>()?;
                for name in &not_names {
                    let reg = world.type_registry.registrations.get(name).ok_or(
                        mlua::Error::RuntimeError(format!("type not registered: {}", name)),
                    )?;
                    not_typeids.push(reg.typeid);
                }

                let query_info = QueryInfo {
                    req_typeids,
                    opt_typeids,
                    not_typeids,
                };
                let dyn_query = ecs_world.dyn_query_mut(&query_info);

                let results = lua.create_table()?;
                for (i, (entity, req_ptrs, opt_ptrs)) in dyn_query.iter().enumerate() {
                    let row = lua.create_table()?;
                    row.set("entity", lua.create_userdata(*entity)?)?;

                    // go through each rquired componnet since its returned per entity
                    for (j, name) in req_names.iter().enumerate() {
                        let reg = world.type_registry.registrations.get(name).unwrap();
                        row.set(
                            name.as_str(),
                            (reg.lua_from_ptr)(req_ptrs[j] as *mut u8, lua)?,
                        )?;
                    }

                    for (j, name) in opt_names.iter().enumerate() {
                        match opt_ptrs[j] {
                            Some(ptr) => {
                                let reg = world.type_registry.registrations.get(name).unwrap();
                                row.set(name.as_str(), (reg.lua_from_ptr)(ptr as *mut u8, lua)?)?;
                            }
                            None => row.set(name.as_str(), mlua::Value::Nil)?,
                        }
                    }

                    results.set(i + 1, row)?;
                }

                Ok(mlua::Value::Table(results))
            },
        );
        methods.add_method(
            "get_component",
            |lua: &mlua::Lua,
             world: &Self,
             (entityid, component_name): (mlua::AnyUserData, mlua::String)|
             -> mlua::Result<mlua::Value> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = *entityid.borrow::<EntityId>()?;
                let type_name: &str = &component_name.to_str()?;
                let registry = world.type_registry.registrations.get(type_name).ok_or(
                    mlua::Error::RuntimeError("component type not registered".to_string()),
                )?;
                let type_id = registry.typeid;

                let component_ptr = ecs_world.get_component_dyn(entity, type_id);

                match component_ptr {
                    Some(ptr) => (registry.lua_from_ptr)(ptr, lua),
                    None => Ok(mlua::Value::Nil),
                }
            },
        );
        methods.add_method(
            "add_component",
            |_lua: &mlua::Lua,
            world: &Self,
            (entityid, value, component_name): (mlua::AnyUserData, mlua::Value, mlua::String)|
            -> mlua::Result<()> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = *entityid.borrow::<EntityId>()?;
                let type_name: &str = &component_name.to_str()?;
                let registry = world.type_registry.registrations.get(type_name)
                        .ok_or(mlua::Error::RuntimeError(format!(
                                    "type not registered: {}", type_name
                        )))?;

                let component = if matches!(value, mlua::Value::Nil) {
                    let constructor = registry.default_construct;
                    match constructor {
                        Some(constructor) => {
                            println!("nil passed for {}, constructing default", type_name);
                            constructor()
                        },
                        None => return Err(mlua::Error::RuntimeError(
                                format!("nil passed for {} but it has no default constructor, construct one explicitly", type_name)
                        )),
                    }
                } else {
                    let converter = registry.dyn_from_lua;
                    (converter)(&value)?
                };

                component
                    .add_to_world(ecs_world, entity)
                    .ok()
                    .ok_or(mlua::Error::RuntimeError(format!(
                                "failed to add component to world: entity: {:?}, type: {}",
                                entity, type_name
                    )))?;
                Ok(())
            },
        );
    }
}
impl mlua::UserData for LuaEngine {}

pub trait PrintOnError {
    fn print_on_error(self);
}

impl<T, E: std::fmt::Debug> PrintOnError for Result<T, E> {
    fn print_on_error(self) {
        if let Err(e) = self {
            eprintln!("Error: {:?}", e);
        }
    }
}
// manual impls for basic types
#[derive(Clone)]
struct Rotor3Lua {
    roll: f32,
    pitch: f32,
    yaw: f32,
}

impl ::mlua::UserData for Rotor3Lua {
    fn add_fields<F: ::mlua::UserDataFields<Self>>(fields: &mut F) {
        fields.add_field_method_get("roll", |_, this| Ok(this.roll));
        fields.add_field_method_set("roll", |_, this, val: f32| {
            this.roll = val;
            Ok(())
        });
        fields.add_field_method_get("pitch", |_, this| Ok(this.pitch));
        fields.add_field_method_set("pitch", |_, this, val: f32| {
            this.pitch = val;
            Ok(())
        });
        fields.add_field_method_get("yaw", |_, this| Ok(this.yaw));
        fields.add_field_method_set("yaw", |_, this, val: f32| {
            this.yaw = val;
            Ok(())
        });
    }
}

impl LuaSeralize for uv::Rotor3 {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        let (roll, pitch, yaw) = match value {
            ::mlua::Value::UserData(ud) => {
                let r = ud.borrow::<Rotor3Lua>()?;
                (r.roll, r.pitch, r.yaw)
            }
            ::mlua::Value::Table(t) => (t.get("roll")?, t.get("pitch")?, t.get("yaw")?),
            _ => {
                return Err(::mlua::Error::RuntimeError(format!(
                    "expected Rotor3 userdata or table, found {}",
                    value.type_name()
                )))
            }
        };
        Ok(uv::Rotor3::from_euler_angles(roll, pitch, yaw))
    }
    fn to_lua(&mut self, lua: &::mlua::Lua) -> ::mlua::Result<::mlua::Value> {
        let mat = self.into_matrix();
        let pitch = mat.cols[2].y.asin();
        let yaw = (-mat.cols[2].x).atan2(mat.cols[2].z);
        let roll = (-mat.cols[0].y).atan2(mat.cols[1].y);
        let ud = lua.create_userdata(Rotor3Lua { roll, pitch, yaw })?;
        Ok(::mlua::Value::UserData(ud))
    }
}
inventory::submit! {LuaTypeDoc{
    name: "Rotor3",
    fields: &[("pitch", "f32"),("yaw", "f32"), ("roll", "f32") ]
}}

impl LuaSeralize for f32 {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Number(n) => Ok(*n as f32),
            mlua::Value::Integer(n) => Ok(*n as f32),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for f32, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, _lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Number(*self as f64))
    }
}
impl LuaSeralize for uv::Vec3 {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        let table = value.as_table().ok_or_else(|| {
            mlua::Error::RuntimeError(format!(
                "number field was of the wrong type: {}",
                value.type_name()
            ))
        })?;

        Ok(uv::Vec3::new(
            table.get("x")?,
            table.get("y")?,
            table.get("z")?,
        ))
    }

    fn to_lua(&mut self, lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        let table = lua.create_table()?;
        table.set("x", self.x)?;
        table.set("y", self.y)?;
        table.set("z", self.z)?;
        Ok(mlua::Value::Table(table))
    }
}

inventory::submit! {LuaTypeDoc{
    name: "Vec3",
    fields: &[("x", "f32"),("y", "f32"), ("z", "f32") ]
}}

impl LuaSeralize for usize {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Integer(n) => Ok(*n as usize),
            mlua::Value::Number(n) => Ok(*n as usize),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for usize, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, _lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Integer(*self as i64))
    }
}
impl LuaSeralize for u32 {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Integer(n) => Ok(*n as u32),
            mlua::Value::Number(n) => Ok(*n as u32),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for usize, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, _lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Integer(*self as i64))
    }
}

impl LuaSeralize for bool {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Boolean(b) => Ok(*b),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected boolean, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, _lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Boolean(*self))
    }
}
impl LuaSeralize for String {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::String(s) => Ok(s.to_string_lossy()),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected string, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::String(lua.create_string(self)?))
    }
}

impl<T: LuaSeralize + Clone> LuaSeralize for Vec<T> {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Table(t) => {
                let mut result = Vec::new();
                for i in 1.. {
                    match t.get::<mlua::Value>(i)? {
                        mlua::Value::Nil => break,
                        v => result.push(T::from_lua(&v)?),
                    }
                }
                Ok(result)
            }
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected table for Vec, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&mut self, lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        let table = lua.create_table()?;
        for (i, item) in self.iter_mut().enumerate() {
            table.set(i + 1, item.to_lua(lua)?)?;
        }
        Ok(mlua::Value::Table(table))
    }
}

impl<T: LuaSeralize> LuaSeralize for Option<T> {
    fn from_lua(value: &mlua::Value) -> mlua::Result<Self> {
        match value {
            mlua::Value::Nil => Ok(None),
            v => Ok(Some(T::from_lua(v)?)),
        }
    }
    fn to_lua(&mut self, lua: &mlua::Lua) -> mlua::Result<mlua::Value> {
        match self {
            Some(v) => v.to_lua(lua),
            None => Ok(mlua::Value::Nil),
        }
    }
}
