use std::{any::TypeId, collections::HashMap, fmt::Debug, hash::Hash, sync::Arc};

use mlua::AnyUserData;
use ultraviolet::{self as uv};

use crate::{
    core::Engine,
    ecs::{DynamicComponent, EntityId, QueryInfo, World},
};

pub struct LuaVM {
    lua: mlua::Lua,
    path: String,
    type_registry: Arc<TypeRegistry>,
    last_modified: std::time::SystemTime,
}

//WARNING: this is duplicated in the proc-macros crate, updates should also go there
fn rust_type_to_lua(rust_type: &str) -> String {
    let split_idx = rust_type
        .find(|c: char| !c.is_alphanumeric() && c != '_')
        .unwrap_or(rust_type.len());

    let (base_type, suffix) = rust_type.split_at(split_idx);

    let lua_type = match base_type {
        "f32" | "f64" | "i32" | "i64" | "u32" | "u64" | "isize" | "usize" => "number",
        "String" => "string",
        "bool" => "boolean",
        other => other,
    };

    format!("{lua_type}{suffix}")
}

pub fn write_lua_docs(path: &str) {
    let mut output = String::new();
    output.push_str("---@meta\n");
    output.push_str("-- This file is auto-generated by the engine. Do not edit.\n\n");

    for reg in inventory::iter::<LuaTypeDoc>() {
        output.push_str(&format!("---@class {}\n", reg.name));
        for (field_name, field_type) in reg.fields {
            output.push_str(&format!(
                "---@field {} {}\n",
                field_name,
                rust_type_to_lua(field_type)
            ));
        }
        output.push('\n');
    }

    for reg in inventory::iter::<LuaUnionDoc>() {
        for (variant_name, data_type) in reg.variants {
            let class_name = format!("{}_{}", reg.name, variant_name);
            output.push_str(&format!("---@class {}\n", class_name));
            output.push_str(&format!("---@field type \"{}\"\n", variant_name));
            if !data_type.is_empty() {
                output.push_str(&format!("---@field data {}\n", rust_type_to_lua(data_type)));
            }
            output.push('\n');
        }

        let union_str = reg
            .variants
            .iter()
            .map(|(v, _)| format!("{}_{}", reg.name, v))
            .collect::<Vec<_>>()
            .join(" | ");
        output.push_str(&format!("---@alias {} {}\n\n", reg.name, union_str));
    }

    std::fs::write(path, output).expect("failed to write lua docs");
}

impl LuaVM {
    pub fn new(path: &str) -> LuaVM {
        write_lua_docs("data/scripts/typedef.lua");
        let lua = mlua::Lua::new();
        let src = std::fs::read_to_string(path).unwrap();
        let err = lua.load(src).exec();
        err.print_on_error();
        dbg!(&path);
        Self {
            lua,
            path: path.to_string(),
            type_registry: Arc::new(TypeRegistry::new()),
            last_modified: std::time::SystemTime::now(),
        }
    }

    pub fn run_script(
        &mut self,
        world: &mut World,
        engine: &mut Engine,
        entry_point: &str,
    ) -> Result<(), mlua::Error> {
        self.maybe_reload()?;
        let function: mlua::Function = self.lua.globals().get(entry_point)?;
        // make the lua user data
        let lua_world_ud = self.lua.create_userdata(LuaWorld {
            world: world as *mut World,
            query_active: false,
            type_registry: self.type_registry.clone(),
        })?;
        let lua_engine_ud = self.lua.create_userdata(LuaEngine {
            engine: engine as *mut Engine,
        })?;
        function.call::<()>((lua_world_ud, lua_engine_ud))?;
        Ok(())
    }

    pub fn maybe_reload(&mut self) -> Result<(), mlua::Error> {
        let modified = std::fs::metadata(&self.path)?.modified()?;
        if modified > self.last_modified {
            let src = std::fs::read_to_string(&self.path)?;
            self.lua.load(src).exec()?;
            self.last_modified = modified;
        }

        Ok(())
    }
}

pub struct LuaWorld {
    pub world: *mut World,
    pub type_registry: Arc<TypeRegistry>,
    query_active: bool,
}
pub struct LuaEngine {
    engine: *mut Engine,
}

pub trait LuaSeralize
where
    Self: Sized,
{
    fn from_lua(value: &mlua::Value, world: &mut World) -> mlua::Result<Self>;
    fn to_lua(&self, lua: &mlua::Lua, world: &mut World) -> mlua::Result<mlua::Value>;
}

pub enum ComponentSource {
    Entity(EntityId),
    Resource,
}

type LuaFromPtrFn = fn(*mut u8, &mlua::Lua) -> mlua::Result<mlua::Value>;
type DynComponentFromLuaFn = fn(&mlua::Value) -> mlua::Result<Box<dyn DynamicComponent>>;
type DefualtConstructFn = fn() -> Box<dyn DynamicComponent>;

pub struct TypeRegistration {
    pub name: &'static str,
    pub typeid: TypeId,
    pub lua_from_entity: fn(EntityId, *mut World, &mlua::Lua) -> mlua::Result<mlua::Value>,
    pub lua_from_resource: fn(*mut World, &mlua::Lua) -> mlua::Result<mlua::Value>,
    pub dyn_from_lua: fn(&mlua::Value, &mut World) -> mlua::Result<Box<dyn DynamicComponent>>,
    pub default_construct: Option<fn() -> Box<dyn DynamicComponent>>,
}

pub struct TypeRegistry {
    pub registrations: HashMap<String, &'static TypeRegistration>,
}

pub struct LuaUnionDoc {
    pub name: &'static str,
    pub variants: &'static [(&'static str, &'static str)], // (variant_name, data_type or "")
}

pub struct LuaTypeDoc {
    pub name: &'static str,
    pub fields: &'static [(&'static str, &'static str)],
}
inventory::collect!(LuaUnionDoc);
inventory::collect!(TypeRegistration);
inventory::collect!(LuaTypeDoc);

impl TypeRegistry {
    fn new() -> Self {
        let mut registrations = HashMap::new();
        for item in inventory::iter::<TypeRegistration>() {
            registrations.insert(item.name.to_string(), item);
        }
        TypeRegistry { registrations }
    }
}

impl mlua::UserData for EntityId {}
impl mlua::UserData for LuaWorld {
    fn add_fields<F: mlua::UserDataFields<Self>>(_fields: &mut F) {}

    fn add_methods<M: mlua::UserDataMethods<Self>>(methods: &mut M) {
        methods.add_method(
            "spawn",
            |lua: &mlua::Lua, world: &Self, name: String| -> mlua::Result<mlua::AnyUserData> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = ecs_world.spawn(&name);
                lua.create_userdata(entity)
            },
        );
        methods.add_method("despawn", |_lua, world, id: AnyUserData| {
            let entity = *id.borrow::<EntityId>()?;
            let ecs_world = unsafe { &mut *world.world };
            ecs_world
                .despawn(entity)
                .map_err(|e| mlua::Error::RuntimeError(format!("{:?}", e)))?;
            Ok(())
        });
        methods.add_method(
            "get_resource",
            |lua, world, name: String| -> mlua::Result<mlua::Value> {
                let reg = world
                    .type_registry
                    .registrations
                    .get(&name)
                    .ok_or_else(|| {
                        mlua::Error::RuntimeError(format!("not registered: {}", name))
                    })?;
                (reg.lua_from_resource)(world.world, lua)
            },
        );
        methods.add_method(
            "query",
            |lua: &mlua::Lua, world: &Self, query: mlua::Table| -> mlua::Result<mlua::Value> {
                let ecs_world = unsafe { &mut *world.world };

                // helper to resolve a list of type names to registrations + typeids
                let resolve_names = |names: Vec<String>| -> mlua::Result<
                    Vec<(String, &'static TypeRegistration, TypeId)>,
                > {
                    names
                        .into_iter()
                        .map(|name| {
                            let reg =
                                world
                                    .type_registry
                                    .registrations
                                    .get(&name)
                                    .ok_or_else(|| {
                                        mlua::Error::RuntimeError(format!(
                                            "type not registered: {}",
                                            name
                                        ))
                                    })?;
                            let typeid = reg.typeid;
                            Ok((name, *reg, typeid))
                        })
                        .collect()
                };

                let req = resolve_names(
                    query
                        .get::<mlua::Table>("req")
                        .unwrap_or(lua.create_table()?)
                        .sequence_values::<String>()
                        .collect::<mlua::Result<_>>()?,
                )?;

                let opt = resolve_names(
                    query
                        .get::<mlua::Table>("opt")
                        .unwrap_or(lua.create_table()?)
                        .sequence_values::<String>()
                        .collect::<mlua::Result<_>>()?,
                )?;

                let not = resolve_names(
                    query
                        .get::<mlua::Table>("not")
                        .unwrap_or(lua.create_table()?)
                        .sequence_values::<String>()
                        .collect::<mlua::Result<_>>()?,
                )?;

                let query_info = QueryInfo {
                    req_typeids: req.iter().map(|(_, _, id)| *id).collect(),
                    opt_typeids: opt.iter().map(|(_, _, id)| *id).collect(),
                    not_typeids: not.iter().map(|(_, _, id)| *id).collect(),
                };

                let dyn_query = ecs_world.dyn_query_mut(&query_info);
                let results = lua.create_table()?;

                for (i, (entity, _req_ptrs, _opt_ptrs)) in dyn_query.iter().enumerate() {
                    let row = lua.create_table()?;
                    row.set("entity", lua.create_userdata(*entity)?)?;

                    for (name, reg, _) in &req {
                        row.set(
                            name.as_str(),
                            (reg.lua_from_entity)(*entity, world.world, lua)?,
                        )?;
                    }

                    for (name, reg, _) in &opt {
                        let value = (reg.lua_from_entity)(*entity, world.world, lua)
                            .ok()
                            .unwrap_or(mlua::Value::Nil);
                        row.set(name.as_str(), value)?;
                    }

                    results.set(i + 1, row)?;
                }

                Ok(mlua::Value::Table(results))
            },
        );
        methods.add_method(
            "get_component",
            |lua: &mlua::Lua,
             world: &Self,
             (entityid, component_name): (mlua::AnyUserData, mlua::String)|
             -> mlua::Result<mlua::Value> {
                let entity = *entityid.borrow::<EntityId>()?;
                let type_name: &str = &component_name.to_str()?;
                let registry = world.type_registry.registrations.get(type_name).ok_or(
                    mlua::Error::RuntimeError("component type not registered".to_string()),
                )?;

                (registry.lua_from_entity)(entity, world.world, lua).map_err(|x| {
                    mlua::Error::RuntimeError(format!("get component failed with {:?}", x))
                })
            },
        );
        methods.add_method(
            "find",
            |lua: &mlua::Lua, world: &Self, name: String| -> mlua::Result<mlua::Value> {
                let ecs_world = unsafe { &mut *world.world };
                match ecs_world.find(&name) {
                    Some(entity) => Ok(mlua::Value::UserData(lua.create_userdata(entity)?)),
                    None => Ok(mlua::Value::Nil),
                }
            },
        );
        methods.add_method(
            "add_component",
            |_lua: &mlua::Lua,
            world: &Self,
            (entityid, value, component_name): (mlua::AnyUserData, mlua::Value, mlua::String)|
            -> mlua::Result<()> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = *entityid.borrow::<EntityId>()?;
                let type_name: &str = &component_name.to_str()?;
                let registry = world.type_registry.registrations.get(type_name)
                        .ok_or(mlua::Error::RuntimeError(format!(
                                    "type not registered: {}", type_name
                        )))?;

                let component = if matches!(value, mlua::Value::Nil) {
                    let constructor = registry.default_construct;
                    match constructor {
                        Some(constructor) => {
                            println!("nil passed for {}, constructing default", type_name);
                            constructor()
                        },
                        None => return Err(mlua::Error::RuntimeError(
                                format!("nil passed for {} but it has no default constructor, construct one explicitly", type_name)
                        )),
                    }
                } else {
                    let converter = registry.dyn_from_lua;
                    (converter)(&value, ecs_world)?
                };

                component
                    .add_to_world(ecs_world, entity)
                    .ok()
                    .ok_or(mlua::Error::RuntimeError(format!(
                                "failed to add component to world: entity: {:?}, type: {}",
                                entity, type_name
                    )))?;
                Ok(())
            },
        );
        methods.add_method(
            "remove_component",
            |_lua: &mlua::Lua,
             world: &Self,
             (entityid, component_name): (mlua::AnyUserData, mlua::String)|
             -> mlua::Result<()> {
                let ecs_world = unsafe { &mut *world.world };
                let entity = *entityid.borrow::<EntityId>()?;
                let type_name: &str = &component_name.to_str()?;
                let registry = world.type_registry.registrations.get(type_name).ok_or(
                    mlua::Error::RuntimeError(format!("type not registered: {}", type_name)),
                )?;

                ecs_world
                    .remove_dyn(entity, registry.typeid)
                    .map_err(|err| {
                        mlua::Error::RuntimeError(format!(
                            "failed to add component to world: entity: {:?}, type: {} with err {:?}",
                            entity, type_name, err
                        ))
                    })?;
                Ok(())
            },
        );
    }
}
impl mlua::UserData for LuaEngine {}

pub trait PrintOnError {
    fn print_on_error(self);
}

impl<T, E: std::fmt::Debug> PrintOnError for Result<T, E> {
    fn print_on_error(self) {
        if let Err(e) = self {
            eprintln!("Error: {:?}", e);
        }
    }
}
// manual impls for basic types
#[derive(Clone)]
struct Rotor3Lua {
    roll: f32,
    pitch: f32,
    yaw: f32,
}

impl ::mlua::UserData for Rotor3Lua {
    fn add_fields<F: ::mlua::UserDataFields<Self>>(fields: &mut F) {
        fields.add_field_method_get("roll", |_, this| Ok(this.roll));
        fields.add_field_method_set("roll", |_, this, val: f32| {
            this.roll = val;
            Ok(())
        });
        fields.add_field_method_get("pitch", |_, this| Ok(this.pitch));
        fields.add_field_method_set("pitch", |_, this, val: f32| {
            this.pitch = val;
            Ok(())
        });
        fields.add_field_method_get("yaw", |_, this| Ok(this.yaw));
        fields.add_field_method_set("yaw", |_, this, val: f32| {
            this.yaw = val;
            Ok(())
        });
    }
}

impl LuaSeralize for uv::Rotor3 {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        let (roll, pitch, yaw) = match value {
            ::mlua::Value::UserData(ud) => {
                let r = ud.borrow::<Rotor3Lua>()?;
                (r.roll, r.pitch, r.yaw)
            }
            ::mlua::Value::Table(t) => (t.get("roll")?, t.get("pitch")?, t.get("yaw")?),
            _ => {
                return Err(::mlua::Error::RuntimeError(format!(
                    "expected Rotor3 userdata or table, found {}",
                    value.type_name()
                )));
            }
        };
        Ok(uv::Rotor3::from_euler_angles(roll, pitch, yaw))
    }
    fn to_lua(&self, lua: &::mlua::Lua, _world: &mut World) -> ::mlua::Result<::mlua::Value> {
        let mat = self.into_matrix();
        let pitch = mat.cols[2].y.asin();
        let yaw = (-mat.cols[2].x).atan2(mat.cols[2].z);
        let roll = (-mat.cols[0].y).atan2(mat.cols[1].y);
        let ud = lua.create_userdata(Rotor3Lua { roll, pitch, yaw })?;
        Ok(::mlua::Value::UserData(ud))
    }
}
inventory::submit! {LuaTypeDoc{
    name: "Rotor3",
    fields: &[("pitch", "f32"),("yaw", "f32"), ("roll", "f32") ]
}}

impl LuaSeralize for f32 {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Number(n) => Ok(*n as f32),
            mlua::Value::Integer(n) => Ok(*n as f32),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for f32, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, _lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Number(*self as f64))
    }
}
impl LuaSeralize for uv::Vec3 {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        let table = value.as_table().ok_or_else(|| {
            mlua::Error::RuntimeError(format!(
                "number field was of the wrong type: {}",
                value.type_name()
            ))
        })?;

        Ok(uv::Vec3::new(
            table.get("x")?,
            table.get("y")?,
            table.get("z")?,
        ))
    }

    fn to_lua(&self, lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        let table = lua.create_table()?;
        table.set("x", self.x)?;
        table.set("y", self.y)?;
        table.set("z", self.z)?;
        Ok(mlua::Value::Table(table))
    }
}

inventory::submit! {LuaTypeDoc{
    name: "Vec3",
    fields: &[("x", "f32"),("y", "f32"), ("z", "f32") ]
}}

impl LuaSeralize for usize {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Integer(n) => Ok(*n as usize),
            mlua::Value::Number(n) => Ok(*n as usize),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for usize, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, _lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Integer(*self as i64))
    }
}
impl LuaSeralize for u32 {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Integer(n) => Ok(*n as u32),
            mlua::Value::Number(n) => Ok(*n as u32),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected number for usize, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, _lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Integer(*self as i64))
    }
}

impl LuaSeralize for bool {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Boolean(b) => Ok(*b),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected boolean, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, _lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::Boolean(*self))
    }
}
impl LuaSeralize for String {
    fn from_lua(value: &mlua::Value, _world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::String(s) => Ok(s.to_string_lossy()),
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected string, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, lua: &mlua::Lua, _world: &mut World) -> mlua::Result<mlua::Value> {
        Ok(mlua::Value::String(lua.create_string(self)?))
    }
}

impl<T: LuaSeralize + Clone> LuaSeralize for Vec<T> {
    fn from_lua(value: &mlua::Value, world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Table(t) => {
                let mut result = Vec::new();
                for i in 1.. {
                    match t.get::<mlua::Value>(i)? {
                        mlua::Value::Nil => break,
                        v => result.push(T::from_lua(&v, world)?),
                    }
                }
                Ok(result)
            }
            _ => Err(mlua::Error::RuntimeError(format!(
                "expected table for Vec, found {}",
                value.type_name()
            ))),
        }
    }
    fn to_lua(&self, lua: &mlua::Lua, world: &mut World) -> mlua::Result<mlua::Value> {
        let table = lua.create_table()?;
        for (i, item) in self.iter().enumerate() {
            table.set(i + 1, item.to_lua(lua, world)?)?;
        }
        Ok(mlua::Value::Table(table))
    }
}

impl<T: LuaSeralize> LuaSeralize for Option<T> {
    fn from_lua(value: &mlua::Value, world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Nil => Ok(None),
            v => Ok(Some(T::from_lua(v, world)?)),
        }
    }
    fn to_lua(&self, lua: &mlua::Lua, world: &mut World) -> mlua::Result<mlua::Value> {
        match self {
            Some(v) => v.to_lua(lua, world),
            None => Ok(mlua::Value::Nil),
        }
    }
}
impl<T: LuaSeralize> LuaSeralize for Box<T> {
    fn from_lua(value: &mlua::Value, world: &mut World) -> mlua::Result<Self> {
        Ok(Box::new(T::from_lua(value, world)?))
    }
    fn to_lua(&self, lua: &mlua::Lua, world: &mut World) -> mlua::Result<mlua::Value> {
        (**self).to_lua(lua, world)
    }
}

impl<K, V> LuaSeralize for HashMap<K, V>
where
    K: LuaSeralize + Eq + std::hash::Hash,
    V: LuaSeralize,
{
    fn to_lua(&self, lua: &mlua::Lua, world: &mut World) -> mlua::Result<mlua::Value> {
        let table = lua.create_table()?;

        for (k, v) in self.iter() {
            let key = k.to_lua(lua, world)?;
            let value = v.to_lua(lua, world)?;

            table.set(key, value)?;
        }

        Ok(mlua::Value::Table(table))
    }

    fn from_lua(value: &mlua::Value, world: &mut World) -> mlua::Result<Self> {
        match value {
            mlua::Value::Table(table) => {
                let mut map = HashMap::new();

                for pair in table.pairs::<mlua::Value, mlua::Value>() {
                    let (k, v) = pair?;

                    let key = K::from_lua(&k, world)?;
                    let value = V::from_lua(&v, world)?;

                    map.insert(key, value);
                }

                Ok(map)
            }
            other => Err(mlua::Error::FromLuaConversionError {
                from: other.type_name(),
                to: "HashMap".to_string(),
                message: Some("expected Lua table".into()),
            }),
        }
    }
}
